import { Op } from 'sequelize'
export default {
   database: process.env.DATABASE || "challenge_db",
   username: process.env.USERNAME || "root",
   host: process.env.HOST || "127.0.0.1",
   password: process.env.PASS || "123456",
   dialectOptions: { timezone: "local" },
   pool: { max: 30, min: 1, idle: 1000 },
   timezone: "America/Mexico_City",
   models: [__dirname + '/models'],
   operatorAliases: false,
   dialect: "mysql",
   $like: Op.like,
   logging: true,
   $gte: Op.gte,
   $lte: Op.lte,
   $eq: Op.eq,
   $ne: Op.ne,
   $or: Op.or,
}